### ISSUE TITLE
"Warning" value stays 0 even there is a problem with duplicated cluster name

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#479] opened 2021-11-19 17:41 UTC
see http://13.95.71.67/clusters

We have here duplicated cluster name: drbd_cluster, hana_cluster, Cluster Id are different.
So value of Warning '0' is wrong.

**Comment by stefanotorresi** [comment] 2021-11-22 10:53
It might also be worth nothing that the Alert icon should probably take the place of the grey disc at the beginning of the row.

**Comment by abravosuse** [comment] 2021-11-26 10:15
My two cents on this: for me the "issue" here is that the yellow warning sign informing about a duplicated cluster name might be interpreted as a cluster warning status. I agree with @stefanotorresi that placing the warning sign somewhere else might help but I would suggest choosing an different sign/symbol to notify about the duplicated name.

**Comment by arbulu89** [comment] 2021-11-30 16:14
First things first, as this is not an issue, it is more a UI/UX design topic. @stefanotorresi  Can we first change the labeling so we can have a clear picture of the current state of the project?

**Comment by abravosuse** [comment] 2021-11-30 18:10
@arbulu89 agreed 200% that this not a bug but an UI/UX enhancement.

**Comment by stefanotorresi** [comment] 2021-12-02 14:18
To be honest, I think this _is_ a bug.
If the condition of having duplicate cluster names is a warning, then the warning count should reflect that.

**Comment by fabriziosestito** [comment] 2021-12-02 14:30
@stefanotorresi we choose the warning icon a bit randomly for duplicated clusters without thinking this could appear as a warning, but we are considering only check results as  a warning state in the cluster details too.
I would vote to change the icon to something else, because it can really confuse users.

**Comment by arbulu89** [comment] 2021-12-02 14:31
> To be honest, I think this _is_ a bug.
> 
> If the condition of having duplicate cluster names is a warning, then the warning count should take that into account. If the users sees warning count 0, but then warnings in the rows, then something is wrong.
> 
> Why do you guys think this is not a bug?

Because it was implemented this way intentionally since the beginning. In the beginning, we didn't have the `id` column as we have now, so it was not really possible to know which cluster you were using, so to highlight that they were 2 in reality, we put the icon.
If you want, we can remove the icon completely.

**Comment by stefanotorresi** [comment] 2021-12-02 14:38
Yeah, maybe we should implement this as a check, somehow. Let's change the icon for now, so that this appears not as a warning, but something even softer, like a notice.

**Comment by arbulu89** [comment] 2021-12-03 15:57
@stefanotorresi @abravosuse Does this look OK by now?
![image](https://user-images.githubusercontent.com/36370954/144632924-79f73e6f-872f-4000-bd57-7f9ef9823d70.png)

**Comment by abravosuse** [comment] 2021-12-03 17:27
Yes, @arbulu89 that new icon looks great to me. It prompts you to check it out but doesn't make you think of a warning.

**Comment by stefanotorresi** [comment] 2021-12-10 10:36
fixed by 5bfa2ec99cb4399f4a5f9aba5f3d19b8f9d29951

**Closed by stefanotorresi** 2021-12-10 10:36 UTC
Labels: enhancement, UI/UX
