### ISSUE TITLE
Hosts -Filters - field with selected items stays forever

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#597] opened 2021-12-17 08:43 UTC
Testing 3nd round for v0.6.0
trento server: v0.6.0+git.dev282.1639671445.67f8ba5

Go to QA trento server: http://20.126.10.94/hosts

Select any item in filters 'Passing', 'Warning', 'Critical' or SAP Systems 'HDD'. The field with selected items just stays, not closed as expected. It disappears and reloads the page if I click somewhere on the page.
see screenshot:

![hosts-filters-1](https://user-images.githubusercontent.com/4113246/146515465-e9917cd7-1f3d-4915-9363-e783cd8da11f.jpg)

**Comment by arbulu89** [comment] 2021-12-17 08:49
I would say this is an expected behaviour, as they are multiselect checkboxes and the user might want to select multiple of them in one shot. I don't see it wrong at least.
Anyway, I guess there would be some solution if the product owner thinks that this must be changed

**Comment by abravosuse** [comment] 2021-12-19 16:23
v0.7.0: same behavior as in v0.6.0+git.dev282.1639671445.67f8ba5 but I agree with @arbulu89 that this gives the user the opportunity to select multiple values. I don't see it wrong either.

**Comment by fabriziosestito** [comment] 2021-12-20 08:03
Not a bug, closing

**Closed by fabriziosestito** 2021-12-20 08:03 UTC
Labels: wontfix
