### ISSUE TITLE
Peacemaker Clusters details - Health - Show check reults doesn't provide any information about host

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#550] opened 2021-12-09 14:52 UTC
trento server v0.6.0

Go to http://20.67.108.123/clusters/fec8df5108277914a595f2262400a8b9 and click on 'Show check results'.

I cannot find any useful information expect both hosts. And 'Filter the checks lists' seem to be not working neither.

**Comment by abravosuse** [comment] 2021-12-14 11:02
Duplicate of #507

**Comment by fabriziosestito** [comment] 2021-12-14 16:46
Closing, duplicate

**Closed by fabriziosestito** 2021-12-14 16:46 UTC
